name: flutter_example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  auto_route: ^9.2.2
  dio: ^5.7.0
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_form_builder: ^9.3.0
  fluttertoast: ^8.2.8
  form_builder_validators: ^11.0.0
  get_it: ^7.7.0
  injectable: ^2.4.4
  json_annotation: ^4.9.0
  logger: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.9
  drift_dev: ^2.20.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
